### ISSUE TITLE
update cache via restful interface - protected by login

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/dblpconf#18]
to make sure we have the current data

**Comment by MusaabKh** [comment]
Should the cache store should be directed to orclone instead of the original open research?

**Comment by WolfgangFahl** [comment]
orclone for dblpconf is better at this time

**Comment by WolfgangFahl** [comment]
work around this issue for testing agains pymediawikidocker based images  by using docker image #20
