### ISSUE TITLE
refactor to new SPARQL/justpy architecture

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/dblpconf#21]
Make EventSeries and Event Data of dblp available and searchable for a start.

Use as a playground/research area to check new software architecture approach that is graph-based and not table based.
Navigation options to neighbours such as authors/papers would be nice.

**Comment by WolfgangFahl** [comment]
move demo to new server is main goal!

**Comment by tholzheim** [comment]
Query for the front page https://confident.dbis.rwth-aachen.de/dblpconf/
```sparql
PREFIX dblp: <https://dblp.org/rdf/schema#>
SELECT ?conf 
       (IRI(CONCAT("https://dblp.org/db/conf/", ?conf, "/index.html")) as ?dblp)
       (MIN(xsd:integer(?year)) AS ?minYear) 
       (MAX(xsd:integer(?year)) AS ?maxYear) 
       (COUNT(?conf) as ?count)
       (IRI(CONCAT("https://confident.dbis.rwth-aachen.de/dblpconf/series/", ?conf)) as ?series)
WHERE
{
    SELECT 
        (strbefore(REPLACE(STR(?p), "https://dblp.org/rec/conf/", "", "i"), "/") as ?conf)
        ?year
    WHERE {
        ?p a dblp:Editorship .
        OPTIONAL{?p dblp:yearOfPublication ?year}
        FILTER(strstarts(STR(?p), "https://dblp.org/rec/conf/"))
    }
}
GROUP BY ?conf
ORDER BY ?conf
LIMIT 20000
```

> Runs with stardog (QLever does not support all used string functions)

Result (excerpt):
conf | dblp | minYear | maxYear | count | series
-- | -- | -- | -- | -- | --
3dgis | https://dblp.org/db/conf/3dgis/index.html | 2006 | 2006 | 1 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dgis
3dic | https://dblp.org/db/conf/3dic/index.html | 2009 | 2021 | 9 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dic
3dica | https://dblp.org/db/conf/3dica/index.html | 1997 | 2020 | 19 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dica
3dim | https://dblp.org/db/conf/3dim/index.html | 1997 | 2021 | 18 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dim
3dor | https://dblp.org/db/conf/3dor/index.html | 2008 | 2021 | 14 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dor
3dph | https://dblp.org/db/conf/3dph/index.html | 2009 | 2009 | 1 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dph
3dpvt | https://dblp.org/db/conf/3dpvt/index.html | 2002 | 2006 | 3 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dpvt
3dtv | https://dblp.org/db/conf/3dtv/index.html | 2012 | 2018 | 7 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dtv
3dui | https://dblp.org/db/conf/3dui/index.html | 2006 | 2017 | 12 | https://confident.dbis.rwth-aachen.de/dblpconf/series/3dui
ACISicis | https://dblp.org/db/conf/ACISicis/index.html | 2005 | 2021 | 17 | https://confident.dbis.rwth-aachen.de/dblpconf/series/ACISicis
ACMace | https://dblp.org/db/conf/ACMace/index.html | 2004 | 2018 | 15 | https://confident.dbis.rwth-aachen.de/dblpconf/series/ACMace
aPcsac | https://dblp.org/db/conf/aPcsac/index.html | 2000 | 2008 | 8 | https://confident.dbis.rwth-aachen.de/dblpconf/series/aPcsac
aaa-idea | https://dblp.org/db/conf/aaa-idea/index.html | 2006 | 2006 | 2 | https://confident.dbis.rwth-aachen.de/dblpconf/series/aaa-idea
aaai | https://dblp.org/db/conf/aaai/index.html | 1980 | 2022 | 117 | https://confident.dbis.rwth-aachen.de/dblpconf/series/aaai
aaaifs | https://dblp.org/db/conf/aaaifs/index.html | 2004 | 2022 | 65 | https://confident.dbis.rwth-aachen.de/dblpconf/series/aaaifs
aaaiss | https://dblp.org/db/conf/aaaiss/index.html | 2005 | 2022 | 80 | https://confident.dbis.rwth-aachen.de/dblpconf/series/aaaiss
